version: '3.8'

services:
  api:
    environment:
      - MODE=api
      - APP_NAME=${APP_NAME}
      - DEFAULT_LARGE_MODEL=${DEFAULT_LARGE_MODEL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_BUCKET_NAME=${SUPABASE_BUCKET_NAME}
      - SENTRY_DSN=${SENTRY_DSN}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}
    ports:
      - "8000:8000"

  worker:
    environment:
      - MODE=worker
      - APP_NAME=${APP_NAME}
      - DEFAULT_LARGE_MODEL=${DEFAULT_LARGE_MODEL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_BUCKET_NAME=${SUPABASE_BUCKET_NAME}
      - SENTRY_DSN=${SENTRY_DSN}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}

#  flower:
#    environment:
#      - BROKER_URL=${CELERY_BROKER_URL}
#    ports:
#      - "5555:5555"
